spring:
  application:
    name: duck-chess

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  jwt:
    expiration-days: 7
  verification:
    expiration-minutes: 60
    unverified-user-expiration-days: 7
    password-reset-expiration-minutes: 30